language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker

script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - mvn clean install docker:build -DskipTests -Pdefault,docker
  - mvn deploy -DskipTests -Pdocker

after_success:
  - docker tag marketreaction/api-acceptance-tests:$TRAVIS_BUILD_NUMBER marketreaction/api-acceptance-tests:latest
  - docker push marketreaction/api-acceptance-tests:latest
