language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker

script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - mvn clean install docker:build -DskipTests -Pdefault,docker

after_success:
  - mvn deploy -DskipTests -Pdocker
